# Generated by Django 4.1 on 2022-08-16 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("musicians", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=50)),
                ("published_date", models.DateField(null=True)),
                (
                    "musician",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="musicians.musician",
                    ),
                ),
            ],
        ),
    ]
